name: PunchEffects
version: 0.9.0
author: ZeTioZ
main: fr.zetioz.puncheffects.legacy.Main
website: https://reyna.tk/
softdepend: [WorldGuard]
commands:
  puncheffects:
    aliases: [pe, zpe]
    description: Punch Effects main command