name: PunchEffects
version: 0.8.0
author: ZeTioZ
main: fr.zetioz.puncheffects.Main
website: https://opsycraft.fr/
softdepend: [WorldGuard]
commands:
  puncheffects:
    aliases: [pe, zpe]
    description: Punch Effects main command