name: PunchEffects
version: 1.0.0
author: ZeTioZ
main: fr.zetioz.puncheffects.PunchEffectsMain
website: https://github.com/ZeTioZ/PunchEffects
api-version: 1.17
softdepend: [WorldGuard, PlaceholderAPI]
commands:
  puncheffects:
    aliases: [pe, zpe]
    description: Punch Effects main command